version: '3.6'
services:

  app:
    build:
      context: .
    tty: true
    expose:
      - 3000
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: yarn dev
    
volumes:
  node_modules:
    driver: local